name: Build and Release

on:
  push:
    tags:
      - 'v*' # fx v1.0.0

jobs:
  release:
    name: Build Windows Release
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: cargo build --release

      - name: Zip release files (Windows)
        shell: pwsh
        run: Compress-Archive -Path target/release/PlaywrightDebugMover.exe, templates/test.spec.ts -DestinationPath PlaywrightDebugMover.zip


      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: PlaywrightDebugMover.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
